config/routes.rb
Rails.application.routes.draw do
  resources :est
  resources :buys
  root "est#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
  validates :category, :description, :amount, presence: true  
end

app/models/est.rb
class Est < ApplicationRecord
  validates :nombres, :apellidos, :carrera, :carnet, :nacimiento, :celular, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buy_params
      params.require(:buy).permit(:category, :description, :amount)
    end
end

app/controllers/ests_controller.rb
class EstsController < ApplicationController
  before_action :set_est, only: [:show, :edit, :update, :destroy]

  # GET /ests
  # GET /ests.json
  def index
    @ests = Est.all
  end

  # GET /ests/1
  # GET /ests/1.json
  def show
  end

  # GET /ests/new
  def new
    @est = Est.new
  end

  # GET /ests/1/edit
  def edit
  end

  # POST /ests
  # POST /ests.json
  def create
    @est = Est.new(est_params)

    respond_to do |format|
      if @est.save
        format.html { redirect_to @est, notice: 'Est was successfully created.' }
        format.json { render :show, status: :created, location: @est }
      else
        format.html { render :new }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ests/1
  # PATCH/PUT /ests/1.json
  def update
    respond_to do |format|
      if @est.update(est_params)
        format.html { redirect_to @est, notice: 'Est was successfully updated.' }
        format.json { render :show, status: :ok, location: @est }
      else
        format.html { render :edit }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ests/1
  # DELETE /ests/1.json
  def destroy
    @est.destroy
    respond_to do |format|
      format.html { redirect_to ests_url, notice: 'Est was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_est
      @est = Est.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def est_params
      params.require(:est).permit(:nombres, :apellidos, :carrera, :carnet, :nacimiento, :celular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/ests_helper.rb
module EstsHelper
end

app/views/buys/_form.html.erb
<%= form_with(model: buy) do |form| %>
  <% if buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
        <% buy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buys</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.category %></td>
        <td><%= buy.description %></td>
        <td><%= buy.amount %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @buy.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @buy.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @buy.amount %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>

app/views/ests/_form.html.erb
<%= form_with(model: est) do |form| %>
  <% if est.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(est.errors.count, "error") %> prohibited this est from being saved:</h2>

      <ul>
        <% est.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :carrera %>
    <%= form.text_field :carrera %>
  </div>

  <div class="field">
    <%= form.label :carnet %>
    <%= form.text_field :carnet %>
  </div>

  <div class="field">
    <%= form.label :nacimiento %>
    <%= form.date_select :nacimiento %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.number_field :celular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ests/edit.html.erb
<h1>Editing Est</h1>

<%= render 'form', est: @est %>

<%= link_to 'Show', @est %> |
<%= link_to 'Back', ests_path %>

app/views/ests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ests</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Carrera</th>
      <th>Carnet</th>
      <th>Nacimiento</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ests.each do |est| %>
      <tr>
        <td><%= est.nombres %></td>
        <td><%= est.apellidos %></td>
        <td><%= est.carrera %></td>
        <td><%= est.carnet %></td>
        <td><%= est.nacimiento %></td>
        <td><%= est.celular %></td>
        <td><%= link_to 'Show', est %></td>
        <td><%= link_to 'Edit', edit_est_path(est) %></td>
        <td><%= link_to 'Destroy', est, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Est', new_est_path %>

app/views/ests/new.html.erb
<h1>New Est</h1>

<%= render 'form', est: @est %>

<%= link_to 'Back', ests_path %>

app/views/ests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @est.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @est.apellidos %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @est.carrera %>
</p>

<p>
  <strong>Carnet:</strong>
  <%= @est.carnet %>
</p>

<p>
  <strong>Nacimiento:</strong>
  <%= @est.nacimiento %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @est.celular %>
</p>

<%= link_to 'Edit', edit_est_path(@est) %> |
<%= link_to 'Back', ests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppScaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>